spring:
  datasource:
    url: jdbc:mysql://localhost:3306/minutes?serverTimezone=UTC&characterEncoding=utf8
    username: minutes
    password: minutes1234
    driver-class-name: com.mysql.cj.jdbc.Driver

repository:
  rootPath: /home/biz/minutes-admin
  uploadPath: /upload
  location: file:/home/biz/minutes-admin/upload/