spring:
  datasource:
    #url: jdbc:mysql://10.122.64.152:3306/CAMS?serverTimezone=UTC
    url: jdbc:log4jdbc:mysql://222.239.249.197:3306/CAMS?serverTimezone=UTC&characterEncoding=UTF8
    #url: jdbc:log4jdbc:mysql://192.168.1.18:3306/CAMS?serverTimezone=UTC&characterEncoding=UTF8
    username: root
    password: ehdduf922
    #driver-class-name: com.mysql.cj.jdbc.Driver
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
  main:
    banner-mode: "off"
    allow-bean-definition-overriding: true

repository:
  rootPath: E:/
  uploadPath: /upload
  location: file:/E://upload/


logging:
  level:
    jdbc.sqltiming: DEBUG
    org:
      springframework:
        web: DEBUG
        security: DEBUG
    com.zaxxer.hikari.HikariDataSource: DEBUG



